# Generated by Django 5.0.2 on 2024-03-06 19:03

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('orig_doc_date', django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
    ]
